name: Update Readme with IP Addresses

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: # 允许手动触发

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          node-version: '20'  

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          node-version: '20'  
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Run the script and capture output
      - name: Run the script
        run: |
          python main.py

      # Update README with the IP addresses
      - name: Update README.md
        run: |
          echo "# GitHub URLs and Their IP Addresses" > README.md
         
